### ISSUE TITLE
Unable to interact with Frogg Furnishing

### ISSUE THREAD

**Issue by AquamarineTheBat** [LeDrascol/Spooky-Tweaks#1]
**Describe the bug**
Cant interact with Frogg Furniture 
**Game Log**
Related information from the game's log file.
[starbound.log](https://github.com/LeDrascol/Spooky-Tweaks/files/3379717/starbound.log)

**Comment by LeDrascol** [comment]
Issue was confirmed and fixed. This mod's Frogg Furnishing items will appear under their own custom tab. The issue will remain in your game until the mod is updated _with_ the fix posted here.
